# Generated by Django 5.1 on 2025-02-04 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopsales", "0005_sale_saleitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="sale",
            name="amount_received",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="sale",
            name="change_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
